---
- name: Converge
  hosts: all
  become: true

  vars:
    lego_stop_start_services:
      - not_installed_yet_but_ignore_errors

  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
